### ISSUE TITLE
infinite scrolling within a specific div? 

### ISSUE THREAD

**Issue by tylerstraub** [alethes/meteor-pages#10]
I have a requirement to create infinite scrolling, paginated content within a scrolling div (the body does not scroll, but a smaller box inside the body does).  

It seems like by default this package listens to the body scroll state to determine when it's time to load more content to the client. 

Can this be modified to listen to a different div? Perhaps it would be a good to add another configuration setting to allow this to be specified? 

Thanks!

**Comment by mccormjt** [comment]
Definitely would like to see this feature added as well! Would make this much more useful. I might go about implementing this myself if there arn't any new updates on it?

**Comment by dandv** [comment]
@tylerstraub: what is the resolution on this? The commit above doesn't actually fix the issue.
