### ISSUE TITLE
Stop subscriptions for pages outside of dataMargin

### ISSUE THREAD

**Issue by cherbst** [alethes/meteor-pages#100]
I had expected that subscriptions to pages outside of the range of currentPage +/- dataMargin are automatically stopped. But this does not seem to be the case. When fetching pages with iron router integration, neighboring pages are subscribed to correctly, but pages which get outside of the data margin and are no longer  neighboring pages do not get unsubscribed.
This leads to an ever growing number of documents in the client cache.
For big data sets, this also leads to an ever increasing cpu usage of mongodb. 
This can be reproduced very easily when increasing the number of documents e.g. in the "table" example from 1000->100.000 and browsing trough the table.

**Comment by alethes** [comment]
Please check out the new `maxSubscriptions` setting. It defaults to 100.
