### ISSUE TITLE
How the hell Auth function Works?

### ISSUE THREAD

**Issue by voidale** [alethes/meteor-pages#107]
````
userProducts = new Meteor.Collection('userProducts');
userProductsPages = new Meteor.Pagination(userProducts, {
    auth: function(){
         return userProducts.find({userId: this.userId}); <--Why not working?
         //this.Collection.find({userId: this.userId}); or this one
    },
    templateName: "ordersPage"
});
````

**Comment by warsamebashir** [comment]
@artisin Thanks. If you are using something else for pagination, please let me know. I have been hunting for a solution for too long

**Comment by alethes** [comment]
Use the second argument passed to the `auth` function. From the docs:
<cite>
auth (Function, default = undefined) - authorization function called by the built-in publication method with the following arguments:

skip - precalculated number of items to skip based on the number of page being published. Useful when returning a cursor.
subscription - the Meteor subscription object (this in Meteor.publish()). In authenticated connections, subscription.userId holds the currently signed-in user's _id. Otherwise, it's null. The authorization function is called in the context of the Pagination object.
</cite>

That said, the correct way:
```
userProducts = new Meteor.Collection('userProducts');
userProductsPages = new Meteor.Pagination(userProducts, {
    auth: function(skip, sub){
         return userProducts.find({userId: sub.userId}); <--This will work
         //this.Collection.find({userId: sub.userId}); or this one
    },
    templateName: "ordersPage"
});
```

**Comment by hafeez1042** [comment]
After using this code pagination not working, it returns complete data in single page. Without  'auth' it's working perfectly.


    myRequestList = new Meteor.Pagination(Requests, {
	perPage: 2,
        sort: { "timeStamp.createdAt": -1 },
        templateName: "myRequests",
	itemTemplate: "myRequestPagination",
	divWrapper: false,
	auth: function(skip, sub) {
		var currrentUser = sub.userId;
		if (!currrentUser) { return false; }
		return this.Collection.find();
	}
    });

**Comment by Roylib** [comment]
I've used a [similar answer] (https://github.com/alethes/meteor-pages/issues/131) to come up with the usage below.
If anyone has a better solution, please share.

```javascript
this.Houses = new Meteor.Pagination(HousesCollection, {
    templateName: "houses",
  	itemTemplate: "houseItem",
    perPage: 2,
  	sort: { timestamp: -1 },
    auth: function(skip, sub) {
        //Edit custom settings if required:
        var customSettings = {};
        customSettings.fields = {address: 1}; //This is the only field that will be shown
      	customSettings.filters = {baths: 3} //Show houses with 3 baths only

        //Leave this part untouched:
        var fields = customSettings.fields || this.fields
            , sort = customSettings.sort || this.sort //Since I haven't supplied this field, the Pagination sort I've configured above will be used (=2)
            , perPage = customSettings.perPage || this.perPage //Same as the line above
            , _filters = customSettings.filters || this.filters 
            , _options = { fields: fields, sort: sort, limit: perPage, skip: skip };
        return [ _filters, _options ];
    }
});
```
