### ISSUE TITLE
Infinite scrolling doesn't work if your screen is too big to require a scrollbar

### ISSUE THREAD

**Issue by ShimShamSam** [alethes/meteor-pages#11]
When viewing http://pages3.meteor.com/ I have to resize my browser in order to require a scrollbar. Only then does infinite scrolling work. My suggestion is to have a "Load more" button at the bottom so the user can force records to load until there are enough on the page to trigger a scrollbar.

**Comment by GFargo** [comment]
@alethes is it safe to assume this "Load More" feature is postponed for the foreseeable future?

**Comment by davidynamic** [comment]
@alethes I'd also like to know if you have an answer for @GFargo 's question
