### ISSUE TITLE
Meteor-js alethes-pages package, how to implement pageSize dynamically

### ISSUE THREAD

**Issue by Simpanoz** [alethes/meteor-pages#110]
I want to implement changing of pageSize dynamically in my test-app like developer implemented a bar at http://pages2.meteor.com/. But I want to use drop-down select to change the pageSize.

It seems, client side settings are implemented only, if these are placed in 'both' location. If I write code exclusively, on client side, it doesn't work.  
Can some one guide me in this regards.

**Comment by Simpanoz** [comment]
When I tried  older version -> 1.7.1, then client side 'Page set' began to work.

**Comment by alethes** [comment]
It should work in the recent versions. Otherwise, please reopen.
