### ISSUE TITLE
Serious problem in filtering

### ISSUE THREAD

**Issue by babnik63** [alethes/meteor-pages#113]
I have this problem in 1.7.1 and also 1.7.2, but when I upgrade to 1.7.2 all my filters even in server side settings mode  would not work.

I have tried to do it in routsetting instead of client side events but it does not work:

      routeSettings: function(route) {
           console.log("routesettings"+route);    //EVEN this log does not works!!!!!!!!!!!!!
           return this.set("filters",{'title':'/' + 'g' + '/i'});
    }
the log just works if manually set a page number to URL.

when i set the filter options in client side everything disappears. 
this is my code:

client:

     Template.search.events({
    'click #go': function(event) {
        event.preventDefault();

        Pages.set("filters", {
            'title': '/' + 'searchquery' + '/i'
        });

        Pages.reload();
    }
});

and server:
     
     this.Pages = new Meteor.Pagination(items, {
    router: "iron-router",
    homeRoute: ["/search/:city/"],
    route: "/search/:city/",
    // routerTemplate: "search",
    templateName: "search",
    routerLayout: "layout_searchItems",
    perPage: 7,
    itemTemplate: "itemTemplSearch",
    onReloadPage1: true,
    availableSettings: {
        filters: true
    }
});

**Comment by mcrisp** [comment]
I tried to run the multi-collection example by downloading the master.
the ability for the client to set the filter with items_id > 25 does not work.

**Comment by paulbalomiri** [comment]
The little change in the PR above did resolve the problem for me.
The multi-collection example works now.

**Comment by osv** [comment]
Can we bump version?

**Comment by alethes** [comment]
The fix referenced above is incorporated in v1.8.0. In addition, RegExp objects are now converted to a save form (`{$regex: ..., $options: ...}`) before being sent via a method. Calling:
```Pages.set("filters", {name: /a/i})``` will now work.

**Comment by evenfrost** [comment]
It seems that setting regex filters as ```this.set('filters', { name: { $regex: /admin/gi } })``` is not working, as I'm getting ```$regex has to be a string``` MongoError.
Is the only valid syntax ```this.set('filters', { 'whom.name': /admin/gi })```?

**Comment by alethes** [comment]
@evenfrost Either this, or:
```js
this.set('filters', { 'whom.name': {$regex: "admin", $options: "gi" } })
```
What you describe seems to be a *minimongo* or *MongoDB node driver* issue since there's no doubt that [MongoDB supports it](http://docs.mongodb.org/manual/reference/operator/query/regex/).

Anyway, 
```js
this.set('filters', { 'whom.name': /admin/gi })
//or
this.set('filters', { 'whom.name': new RegExp(regExpStr, optionsStr) })
```
seems very convenient.

**Comment by evenfrost** [comment]
Yeah, thanks to know.

**Comment by evenfrost** [comment]
meteor/meteor#346

**Comment by osv** [comment]
good point
