### ISSUE TITLE
Match error: Expected number, got undefined

### ISSUE THREAD

**Issue by 416serg** [alethes/meteor-pages#114]
I have `lib/collections.js`
```
Transfers = new Meteor.Collection('transfers');
Pages = new Meteor.Pagination(Transfers, {
  perPage: 5,
  sort: {
    date: -1
  },
  templateName: 'listTransfers'
});

... some Transfers.allow({})
```

`server/publications.js`
```
Meteor.publish('transfers', function() {
  // return Transfers.find();
  if (this.userId) {
    return Transfers.find({userId: this.userId});
  } else {
    this.ready();
  }
});
```
`listTransfers.html`
```
<template name="listTransfers">
// some html
  {{> pages}}
  {{> pagesNav}}
</template>
```

I am getting the following error 

```
Exception from sub yM3hezX7b6g6wFMn3 Error: Match error: Expected number, got undefined
I20150107-21:32:16.542(-5)?     at checkSubtree (packages/check/match.js:159:1)
I20150107-21:32:16.542(-5)?     at check (packages/check/match.js:32:1)
I20150107-21:32:16.543(-5)?     at Pages.__Pages.Pages.publish (packages/alethes:pages/lib/pages.coffee:477:5)
I20150107-21:32:16.543(-5)?     at [object Object]._handler (packages/alethes:pages/lib/pages.coffee:136:20)
I20150107-21:32:16.543(-5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
I20150107-21:32:16.544(-5)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150107-21:32:16.544(-5)?     at [object Object].subscriptionProto._runHandler (packages/meteorhacks:kadira/lib/hijack/wrap_subscription.js:12:1)
I20150107-21:32:16.545(-5)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150107-21:32:16.545(-5)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150107-21:32:16.545(-5)?     at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:69:1
I20150107-21:32:16.558(-5)? Sanitized and reported to the client as: Match failed [400]
```

**Comment by lc3t35** [comment]
+1 Same for me !

**Comment by ivankravchenko** [comment]
+1
same error at #111

**Comment by sdybskiy** [comment]
hopefully we can see a fix soon :smile:

**Comment by advany** [comment]
any fix? same problem

**Comment by kalarani** [comment]
I had the same problem. There was another message ("Ignoring duplicate publish named 'tasks'") along with this one. Removing the publication for 'tasks' solved this issue for me.

**Comment by rclai** [comment]
I get the same error message, but my table seems to still be working fine.

**Comment by rclai** [comment]
For anyone interested I created a patch to get rid of the error [here](https://github.com/Profab/meteor-pages/commit/6308a3e2ff85c5dfac5923a18de7823e6e2b3769).

**Comment by rclai** [comment]
Using my [DDP inspector](https://github.com/rclai/meteor-ddp-inspector), I saw the root problem:

Initially Pages is sending this subscription with the first parameter as a String. Also I have no idea what that '18963' number represents. It's not the number of documents in my collection.
```
Object {
   msg: "sub", 
   id: "zDWQYwPeHCZmjPYKD", 
   name: "purchaseOrders",  // my collection name
   params: Array[2]
       [
          0: "18963"
          1: undefined
       ]
}
```

**Comment by advany** [comment]
Rclai! you rock :) Hope this gets merged back in soon

**Comment by advany** [comment]
to bad this didn't got included in the latest version

**Comment by rclai** [comment]
Did he fix the issue in his new update, or is the issue still there?

**Comment by samosfator** [comment]
+1
Faced this issue just now. Any workaround?

**Comment by rclai** [comment]
I guess you can try and use my patch.

**Comment by samosfator** [comment]
@rclai I am new to Meteor and not sure what to do with your code snippet.

**Comment by rclai** [comment]
Ok, one second, I will let you know.

**Comment by rclai** [comment]
In your app, create a packages folder, and inside of that folder, git clone this repo, you will notice your app start rebuilding, that means that Meteor will now look at that folder as the new location where the alethes:pages package lives. Then go to my patch, and apply the code in my patch into the pages.coffee file. Does that make sense?

**Comment by samosfator** [comment]
@rclai, definetly yes. Thank you, finally figered it out.

**Comment by samosfator** [comment]
@rclai, definetly yes. Thank you, finally figered it out. Why doesn't that patch among other pull requests?

**Comment by rclai** [comment]
Okay cool. I didn't want to make it a pull request because it's a patch job and thought that @alethes might have a more appropriate fix unless he thinks so and asks to make it a pull request.

**Comment by alethes** [comment]
It might have had something to do with defining the publication with the same name as one defined automatically by `Pages`. In the recent versions, the default publication name is "pages_{{collection_name}}". Previously, it was just the collection name. Usually, there's no need to define a separate publication on the paginated collection, unless you want to use it outside `Pages`.
