### ISSUE TITLE
Is it possible to use customized loading template?

### ISSUE THREAD

**Issue by williamkhshea** [alethes/meteor-pages#117]
Is there any settings option that I can apply my own loading template instead of using the default one?

**Comment by alethes** [comment]
The loading template is used within the page template (which is `_pagesPage` by default):
```
<template name="_pagesPage">
  {{#if ready pagesData}}
  {{else}}
    {{> _pagesLoading}}
  {{/if}}
  {{#each items}}
    {{> item}}
  {{/each}}
</template>
```

In the current version, you can define your own page template and initialize the `Pagination` object with `{pageTemplate: "nameOfYourPageTemplate"}`.

**Comment by manuelmateus16** [comment]
I am trying also to implement a customized loading template. However, when defining a new template for this, following you recommendation:

<template name="novoTemplate">
  {{#if ready pagesData}}
  {{else}}
    LOADINNNNN
  {{/if}}
  {{#each items}}
    {{> item}}
  {{/each}}
</template>

As expected, I get Uncaught Error: No such function: ready nfor not having the ready helper defined within this new template.

How sould it be done to simply customize the loading template?

**Comment by nicksergeant** [comment]
I get the same issue here, too:

![http://i.nick.sg/image/0H2l0y2R1a0D/Image%202015-04-21%20at%207.37.08%20PM.png](http://i.nick.sg/image/0H2l0y2R1a0D/Image%202015-04-21%20at%207.37.08%20PM.png)

**Comment by nicksergeant** [comment]
Ah, changing the template name is going to break all sorts of stuff: https://github.com/alethes/meteor-pages/blob/master/client/controllers.coffee#L31

**Comment by WaSa42** [comment]
It was also an issue for me, but i've found an alternative using **overriding template** from the **[aldeed/meteor-template-extension](https://github.com/aldeed/meteor-template-extension)**

I'm just doing:
```javascript
Template.myTemplate.replaces("_pagesPage");
```

It's not the best way, but the ``pageTemplate`` parameter isn't working for now (or we are missing something).

**Comment by martinwittmann** [comment]
I run into the same problem on trying to use a custom pageTemplate causing missing helpers.

@WaSa42 Is there anything else you changed? I added the package from aldeed and tried replacing _pagesPage but for some reason my pageTemplate still does not inherit the helpers and I get the same error  as @nicksergeant 

    Template.accountLinesPage.replaces('_pagesPage');

Do you have any ideas?

**Comment by martinwittmann** [comment]
My bad: I replaced the _pagesPage template PLUS defined a custom pageTemplate. Sorry :)

**Comment by WaSa42** [comment]
@martinwittmann You didn't replace de right template.
It's not `_pagesPage` but `_pagePages`.

**Comment by WaSa42** [comment]
For more details, here all my code:
```javascript
VideosPages = new Meteor.Pagination(Videos, {
    sort: {
        insertedAt: -1
    },
    perPage: 20,
    infinite:  true,
    divWrapper: 'grid',
    templateName: 'grid',
    itemTemplate:  'videoDisplay'
});
```
I'm using this package for paginate a grid of video with infinite scroll: 
```html
<template name="grid">
    {{> pages}}
</template>
```
But I didn't want the ``{{> _pagesLoading}}`` because I've got my own loader, so I've created a new template:
```html
<template name="videosPages">
    {{#each items}}
        {{> item}}
    {{/each}}
</template>
```

For replacing `pagesPage` template by `videosPages`, I'm using [aldeed/meteor-template-extension](https://github.com/aldeed/meteor-template-extension) in that way in the **grid helper**:
```javascript
Template.accountLinesPage.replaces('_pagesPage');
```

If there is always an error, try to see if the `{pageTemplate: "nameOfYourPageTemplate"}` is no more defined in your collection and if you've wrote the right template name like `'_pagesPage'` and not `'_pagePages'`.

**Comment by martinwittmann** [comment]
@WaSa42 Wow, thank you so much!

**Comment by WaSa42** [comment]
@martinwittmann It's really nothing ;)

**Comment by sachaudh** [comment]
Where am I placing the Template.videoPages.replaces('_pagesPage');
