### ISSUE TITLE
How to use meteor-pages when offline?

### ISSUE THREAD

**Issue by opond** [alethes/meteor-pages#122]
My app have to run when offline, then I use the ground:db package for that purpose. 
When I try to use the meteor-page package, it seem to be the collection was not find form localstorage, so I want to know how to use the meteor-page package with ground db package or anything else that can make my app list a collection when offline.
Thank you.

**Comment by tagrudev** [comment]
I am looking into that too, has anyone implemented meteor-pages successfully with grounddb ?

**Comment by alethes** [comment]
Please check out the newest version of this repository. It should integrate nicely with GroundDB. I made a couple of structural changes and the end product has to be tested before I release it on Atmosphere. There's a GroundDB demo in the *examples* directory.

To install the package directly from the GitHub repo, run:
```
mkdir -p packages
git clone https://github.com/alethes/meteor-pages packages/pages
meteor add alethes:pages
```
from your app's root directory.

I look forward to hearing your feedback.

**Comment by almogdesign** [comment]
Recommend closing this and moving to the following thread / request - https://github.com/alethes/meteor-pages/issues/45

**Comment by alethes** [comment]
I agree.
