### ISSUE TITLE
Pages cursor returns no documents

### ISSUE THREAD

**Issue by centinel3** [alethes/meteor-pages#124]
I have been trying to get data to return using pagination and am missing something. If I log out 'Projects', I don't see any data being returned. On the basic example it has a {{> pages}} reference, though don't see where that template lives, or how it references the collection cursor. Also, I need to limit the Projects collection by companyID. Is there a way to pass that as an argument so that pagination will only return the docs that match? Any help would be appreciated. Thank you in advance! -Chris

lib/collections/projects.js:
ProjectsCollection = new Mongo.Collection('projects');

lib/paginationSettings.js:
Projects = new Meteor.Pagination("ProjectsCollection", {
  itemTemplate: "projectsListTpl",
  perPage: 5
});

client/views/projectsListTpl.html:
<template name="projectsListTpl">
    <div>
      // This is currently undefined due to not knowing where the data is being returned from pagination, or how to assign it to each.
      {{#each projectItems}}
        {{> _projectListItem}}
      {{/each}}
    </div>

    <button class="perPage" data-pp="5">5</button>
    <button class="perPage" data-pp="10">10</button>
</template>

client/views/projectsListTpl.js:
Template.projectsListTpl.events({
    "click .perPage": function(e) {
      var pp;
      pp = $(e.currentTarget).data("pp");
      return Projects.set("perPage", pp);
    }
  });
  Template.projectsListTpl.helpers({
    perPage: function() {
      Session.get(Projects.id + ".ready");
      return Projects.perPage;
    }
  });

**Comment by alethes** [comment]
A couple of pointers:
1. Pass either a variable referencing an existing collection or a string containing a name of the collection you want `pages` to create. In this case, you should have: ```Projects = new Meteor.Pagination(ProjectsCollection, { ...```
2. The *itemTemplate* option specifies a template to be used for each individual item. You don't have to handle the `each` loop. Just define a template that will be rendered for every item and let the package handle the rest.
3. The default template name for the main template is equal to the name of the paginated collection. In the main template, you can put {{> pagesNav}} wherever you want to have a navigation component and {{> pages}} wherever you want the paginated items to be.

I hope you'll find these helpful.

**Comment by centinel3** [comment]
Thank you. Your email notes helped me get it up and running. I hav a couple
follow up questions regarding pagination.

Currently I'm implementing it  like this:

Pages = new Meteor.Pagination(ProjectsCollection, {
auth: function(skip, sub) {
var user = UsersCollection.findOne({_id: sub.userId});
//console.log(user.profile.companyId);
return ProjectsCollection.find({companyId: user.profile.companyId});
},
itemTempalte: "_projectListItem",
templateName: "projectsListTpl",
sort: {sort: {clientName: 1, clientProjectName: 1}},
navShowFirst: false,
navShowLast: false,
paginationMargin: 0,
router: "iron-router",
homeRoute: "/projects-list/",
route: "/projects-list/",
routerTemplate: "projectsListTpl",
routerLayout: "layoutTpl",
perPage: 3,
pageSizeLimit: 3,
});

I have the collection cursor coming back with what appears to be the right
data/filters on companyId, though it's not paginating with 3 per page. All
the data is in one large list. What am I doing wrong?

Also, I'm getting a console error that says: "pathFor couldn't find a route
named "projectsListTpl"" this is on the Iron_core.js file. I'm not sure
what this means.

Thank you for your help with this. This is going to be a great solution for
my project.

Sincerely,
Chris Campbell


On Sat, Feb 21, 2015 at 10:46 AM, alethes <notifications@github.com> wrote:

> A couple of pointers:
> 1. Pass either a variable referencing an existing collection or a string
> containing a name of the collection you want pages to create. In this
> case, you should have: Projects = new
> Meteor.Pagination(ProjectsCollection, { ...
> 2. The *itemTemplate* option specifies a template to be used for each
> individual item. You don't have to handle the each loop. Just define a
> template that will be rendered for every item and let the package handle
> the rest.
> 3. The default template name for the main template is equal to the name of
> the paginated collection. In the main template, you can put {{> pagesNav}}
> wherever you want to have a navigation component and {{> pages}} wherever
> you want the paginated items to be.
>
> I hope you'll find these helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alethes/meteor-pages/issues/124#issuecomment-75377243>
> .
>



-- 
Sincerely,
Chris Campbell

**Comment by centinel3** [comment]
Also, my iron router configuration is below:

this.route('projects-list', {
    name: 'projectsListTpl',
    path: '/projects-list',
    onBeforeAction: function () {
      if (!Roles.userIsInRole(Meteor.user(), 'owner') &&
!Roles.userIsInRole(Meteor.user(), 'admin')) {
        this.render('accessDeniedTpl');
        this.stop();
        return;
      } else {
        this.next();
      }
    },
    waitOn: function() {
      return Meteor.subscribe('colors-used-list');
    },
    data: function() {
      return Meteor.subscribe('projects', Meteor.user().profile.companyId);
    }
  });

On Tue, Mar 3, 2015 at 12:18 PM, Chris Campbell <centinel3@gmail.com> wrote:

> Thank you. Your email notes helped me get it up and running. I hav a
> couple follow up questions regarding pagination.
>
> Currently I'm implementing it  like this:
>
> Pages = new Meteor.Pagination(ProjectsCollection, {
> auth: function(skip, sub) {
> var user = UsersCollection.findOne({_id: sub.userId});
> //console.log(user.profile.companyId);
> return ProjectsCollection.find({companyId: user.profile.companyId});
> },
> itemTempalte: "_projectListItem",
> templateName: "projectsListTpl",
> sort: {sort: {clientName: 1, clientProjectName: 1}},
> navShowFirst: false,
> navShowLast: false,
> paginationMargin: 0,
> router: "iron-router",
> homeRoute: "/projects-list/",
> route: "/projects-list/",
> routerTemplate: "projectsListTpl",
> routerLayout: "layoutTpl",
> perPage: 3,
> pageSizeLimit: 3,
> });
>
> I have the collection cursor coming back with what appears to be the right
> data/filters on companyId, though it's not paginating with 3 per page. All
> the data is in one large list. What am I doing wrong?
>
> Also, I'm getting a console error that says: "pathFor couldn't find a
> route named "projectsListTpl"" this is on the Iron_core.js file. I'm not
> sure what this means.
>
> Thank you for your help with this. This is going to be a great solution
> for my project.
>
> Sincerely,
> Chris Campbell
>
>
> On Sat, Feb 21, 2015 at 10:46 AM, alethes <notifications@github.com>
> wrote:
>
>> A couple of pointers:
>> 1. Pass either a variable referencing an existing collection or a string
>> containing a name of the collection you want pages to create. In this
>> case, you should have: Projects = new
>> Meteor.Pagination(ProjectsCollection, { ...
>> 2. The *itemTemplate* option specifies a template to be used for each
>> individual item. You don't have to handle the each loop. Just define a
>> template that will be rendered for every item and let the package handle
>> the rest.
>> 3. The default template name for the main template is equal to the name
>> of the paginated collection. In the main template, you can put {{>
>> pagesNav}} wherever you want to have a navigation component and {{> pages}}
>> wherever you want the paginated items to be.
>>
>> I hope you'll find these helpful.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/alethes/meteor-pages/issues/124#issuecomment-75377243>
>> .
>>
>
>
>
> --
> Sincerely,
> Chris Campbell
>
>


-- 
Sincerely,
Chris Campbell
