### ISSUE TITLE
Reactive updates with sorting is broken (but I have a fix)

### ISSUE THREAD

**Issue by deanmckee** [alethes/meteor-pages#125]
I've been having problems using pages with my reactive collection.  When I add a new item to a paged collection the sorting ends up out of order in the browser.  I fixed the bug in my local copy of pages but I'm no coffeescript guy.  I think the problem is around line 579 in pages.coffee (in the publish code):

            (@Collection.find get "filters",

If I convert this to javascript I see the following code:

        return (this.Collection.find(get("filters", {

The method invocation of get("filters") is missing a right paren.  It is moved all the way to the end of the return statement.  If I move the paren back to the right place my sort works with reactive updates.

**Comment by alethes** [comment]
Thank you. Fixed in v1.8.3. The issue was exactly where you found it, although the reason was a bit different. The object spanning subsequent lines should have been passed as a second argument to `Collection.find()`. Instead, it was incorrectly passed to the `get()` function.

**Comment by deanmckee** [comment]
This only partially fixes reactive sorting.  For my "Activites" collection, I sort by a datetime field.  With this v1.8.3 fix I now consistently see the newest elements showing up on top (as they should) when I watch reactive updates.

However, instead of pushing/resorting all the elements down (into the past) in a consistent manner, I am seeing jumbling of elements within the paged selection.  I think the code managing the reordering of the sort indexes isn't working quite right.  After this jumbling occurs, when I dump "this.PagedActivities" on the console and look at the PaginatedCollection field I see records with duplicate "_page_activities_i" and "_page_activities_p" values under the _collection _map.

For example (these are two records I pulled out that have duplicate index info in the same PaginatedCollection):

8BTJ23trzw2STDtjH: Object
_id: "8BTJ23trzw2STDtjH"
_pages_activities_i: 1
_pages_activities_p: 1
action: "Logged In"
color: "accent-color"
datetime: Thu Feb 19 2015 14:12:09 GMT-0800 (PST)
id: "YkzSpsTyhdnqtiCXC"
image: "TheEssentials139"
oemId: "4nnLsu8Qiii2EZTAM"
__proto__: Object

jwX43uxwcnP9oYRkc: Object
_id: "jwX43uxwcnP9oYRkc"
_pages_activities_i: 1
_pages_activities_p: 1
action: "Logged In"
color: "accent-color"
datetime: Thu Feb 19 2015 14:12:22 GMT-0800 (PST)
id: "raqeAkgXMBvqZks7B"
image: "TheEssentials139"oemId: "4nnLsu8Qiii2EZTAM"__proto__: Object
