### ISSUE TITLE
Recent changes introduced instability/browser hang

### ISSUE THREAD

**Issue by deanmckee** [alethes/meteor-pages#126]
I've been running version 1.7.2 for a while with no problems.  Recently I updated to 1.82 (and 1.8.3 this morning).  When I do this I notice that my browser now hangs when I have more than one user subscribed to the paged collection.  If I revert back to 1.7.2 the problem goes away.  Both Safari on my Mac laptop and Chrome in linux hang up and bring up the kill page dialog.

**Comment by deanmckee** [comment]
I did a few more tests... the problem happens specifically when I go from version 1.72 to version 1.8.0.

**Comment by deanmckee** [comment]
So I think I know the trigger for this.  In my auth function I return false if a user isn't logged in (the paged data is only available to logged in users).  If I change the return type to an empty array "[]" then things work as expected.  The false value was triggering some path that caused high CPU load/infinite loops?

**Comment by alethes** [comment]
Fixed. Thank you.

**Comment by alethes** [comment]
However, returning an empty array is equivalent to returning `true`, ie allow access to the entire collection. Are you sure that in your app it denies access instead?
