### ISSUE TITLE
changing filters or sort on client side not working

### ISSUE THREAD

**Issue by johntday** [alethes/meteor-pages#127]
using version 1.8.4
whenever i change filters or sort on client side i get the following error:
"Changing filters not allowed"
or
"Changing sort not allowed"

**Comment by alethes** [comment]
Did you explicitly allow those settings while initiating The Pagination object (eg. by passing *availableSettings: {sort: true, filters: true}*)?

**Comment by johntday** [comment]
// both server and client
Diagrams = new Mongo.Collection('diagrams');

DiagramPages = new Meteor.Pagination(Diagrams, {
    templateName: "seqDgmList",
    itemTemplate: "seqDgmListItem",
    dataMargin: 3,
    filters: {},
    onReloadPage1: true,
    paginationMargin: 3,
    fastRender: false,
    perPage: 10
});

// client only
        DiagramPages.set({
            perPage: 10,
            sort: {
                title: -1
            }
        });

**Comment by johntday** [comment]
and the answer is?

**Comment by alethes** [comment]
```
// both server and client
Diagrams = new Mongo.Collection('diagrams');

DiagramPages = new Meteor.Pagination(Diagrams, {
  availableSettings: {
    filters: true,
    settings: true
  },
  templateName: "seqDgmList",
  itemTemplate: "seqDgmListItem",
  dataMargin: 3,
  filters: {},
  onReloadPage1: true,
  paginationMargin: 3,
  fastRender: false,
  perPage: 10
});

// client only
DiagramPages.set({
  perPage: 10,
  sort: {
    title: -1
  }
});
```
