### ISSUE TITLE
How to filter the information using pages

### ISSUE THREAD

**Issue by filipeportes** [alethes/meteor-pages#128]
How can I filter the informations going to the pagination in the server?

**Comment by alethes** [comment]
Check out the *auth* feature. It's used within the internal *Meteor.publish()* call and can limit the result set based on arbitrary criteria. There're several ways to use it. All of them are well-documented.

PS. You can also set the *filters* options to some desired MongoDB find query, unless you want to enable client-side filter modification. If that's the case, use *availableSettings: {filters: true}*. By default, the client isn't allowed to change any settings. The *availableSettings* option let's you define the scope of client permissions. This may be too much information for your use case, so feel free to ignore this paragraph and stick to passing a function to the *auth* option.

**Comment by alethes** [comment]
Please refer to my answer to https://github.com/alethes/meteor-pages/issues/107 as well.

**Comment by filipeportes** [comment]
thanks and sorry for bother again, I understood the auth feature, but it is unavailable to the client, and I'm looking for some way to let the client filter what he is seeing in the pages...
