### ISSUE TITLE
client set method causing a fast redraw, than comeback to old values

### ISSUE THREAD

**Issue by filipeportes** [alethes/meteor-pages#129]
I'm using the cliente set method to set a filter, in the server I hava: 
<code>
Pages = new Meteor.Pagination(Salons, {
    router: "iron-router",

    homeRoute: "/salons/",
    route: "/salons/",
    routerTemplate: "salons",
    routerLayout: "layout",
    itemTemplate: "salonsItem",
    sort: {
        name: 1
    },
    perPage: 20,
    availableSettings: {filters: true, sort: true, perPage: true}});
</code>

and in the client:

<code>
Pages.set({filters: {name: {$regex: new RegExp(Session.get("filter"), "i")}}});
</code>

when the set method is called it seems to apply some changes, but cameback to the default values... the thing is, any attribute passed to the set method is affecting the end result

**Comment by alethes** [comment]
I guess it's about passing a *RegExp* to *$regex*. I'm not sure if minimongo supports it. You try:
```js
Pages.set({filters: {name: {$regex: Session.get("filter"), $options: "i"}}});
```
or
```js
Pages.set({filters: {name: new RegExp(Session.get("filter"), "i")}});
```
The latter syntax works due to `pages` converting it to the former behind the scenes (https://github.com/alethes/meteor-pages/issues/113).

**Comment by filipeportes** [comment]
changed to
<code> Pages.set({filters: {name: {$regex: filter, $options: "i"}}}); </code>
and its working, thanks

**Comment by alethes** [comment]
Good to know!
