### ISSUE TITLE
When try to edit collection, confused ...

### ISSUE THREAD

**Issue by carrot93** [alethes/meteor-pages#130]
this.Pages=new Meteor.Pagination("testdb")

<template name="list">
{{>testdb}}
</template>
<template name="testdb">
{{>pages}}
{{>pagesNav}}
</template>

it's ok. but when I try to operate the collection, so do:
TestDB=new Meteor.Collection("testdb");
this.Pages=new Meteor.Pagination("TestDB")

<template name="list">
....
if  use : " <tempalte name="TestDB"> " ,Says: Typeerror:Template[name] not defined.
....
if use: "<template name="testdb">", nothing happened.

any suggestion?

**Comment by alethes** [comment]
Here's the solution:
```js
TestDB=new Meteor.Collection("testdb");
this.Pages=new Meteor.Pagination(TestDB);
```
