### ISSUE TITLE
Flickering on search

### ISSUE THREAD

**Issue by benjamin79** [alethes/meteor-pages#134]
First i´d like to thank you for the good work.

When i filter the table every row gets removed and is almost instantly rebuild with the result. But this results into a bit of flickering when using a keyup search. I´ve used reactive-table before an didn´t see that behaviour.

When paginating there is no flickering. Why on filter?

This is more a cosmetic issue, but perhaps you or anyone else has an idea have an idea.

**Comment by oskareke** [comment]
How did you solve this?
