### ISSUE TITLE
security concern of exposing the whole collection to client for pagination purpose?

### ISSUE THREAD

**Issue by ZackCaoEsna** [alethes/meteor-pages#135]
Pages = new Meteor.Pagination("collection-name"...)  can only specify db collection rather than filtered subset of db collection, I'm wondering if we may expose unnecessary data to clients? 
For example:
I have db collection Messages {text: "how are you?", userId: "123"} 
I want to paginate all the messages of userId "123" on browser, does meteor-pages expose whole messages collection to the client?  
Does the "filters" already operator on server side to guarantee other user's message records won't come to client? or does the filter only filters data on client side, which implies all data already arrive to the client?
Thanks a lot if anyone can shed some light on it.

**Comment by alethes** [comment]
The filters work primarily on the server. Unless you use availableSettings to allow the client to change them, only the items that match the filtering query will get published. You can also use the auth option to control what's being published based on arbitrary criteria (such as userId). In addition, you can use a function for availableSettings.filters that controls the changes in filters originating from the client side. 

It means you can eg. allow changing the filters, but only if the new ones satisfy some server-imposed criteria.

**Comment by ZackCao** [comment]
alethes, really appreciate your answer!

**Comment by alethes** [comment]
Happy to help.
