### ISSUE TITLE
New to Meteor and need some help to make pagination work

### ISSUE THREAD

**Issue by aurerua** [alethes/meteor-pages#136]
Hi,

I am trying to integrate pagination in an app and can't figure out how to make it work. 
If someone is willing to help, here is what I have before using pagination:

- the way it looks:

![screenshot_addastory_1](https://cloud.githubusercontent.com/assets/10965364/7098188/acec9d70-dfdd-11e4-8a1c-f511bc3de360.png)

- for this I use a collection of stories:
```javascript
Stories = new Mongo.Collection('stories');
```

- a template for displaying one story:
```html
<template name="storyItem">
  <div class="story">
    <div class="story-content">
      <h3>
        <span class="author">{{author}}</span>
      </h3>
      <hr>
      <p><span class="pre" id="story-text">{{content}}</span>
      </p>
    </div>
  </div>
</template>
```

- a template for submitting a new story and displaying **all** submitted stories so far:
```html
<template name="storiesList">
  {{> storySubmit}} <!--the form to add a new story-->
  <div class="stories">
    {{#each stories}}
      {{> storyItem}}
    {{/each}}
  </div>
</template>
```

I want to add pagination to my list of stories. I wish to have the 'Pages Nav' below the existing 'Save' button and the *paginated* stories below that. For this I have changed the "storiesList" template to the following:
```html
<template name="storiesList">
  {{> storySubmit}} <!--the form to add a new story-->
  <div class="stories">
    {{> pages}}
    {{> pagesNav}}
  </div>
</template>
```

and I have tried to put the following lines in different places to make it work, but with no success (nothing gets displayed below the 'Save' button anymore):
this.Pages = new Meteor.Pagination(Stories, {
  itemTemplate: "storyItem"
});

What am I doing wrong?

Thanks in advance,
Aurelien

**Comment by aurerua** [comment]
I've just tried again today and got it working.  

What I have found is that the inclusions ```{{> pages}}``` and ```{{> pagesNav}}``` have to be used within a template, whose name is the "paginated" collection's name. 

So for example it won't work if ```{{> pages}}``` and ```{{> pagesNav}}``` are used directly in another template, like I did yesterday (see code in former post).

It wouldn't work either with the following example, where the template used to include ```{{> pages}}``` and ```{{> pagesNav}}``` has a random name, different from the collection's name:

```js
this.Pages = new Meteor.Pagination(Stories);
```
```html
<div>
  {{> foo}}
</div>

<template name="foo">
  {{> pagesNav}}
  {{> pages}}
</template>
```

**Comment by rizkysyazuli** [comment]
hmm.. i'm a bit confused. what if i have multiple instance of that collection in several places?

**Comment by aurerua** [comment]
@rizkysyazuli : To further clarify my last post: as long as I defined a template like this:
```html
<template name="paginatedCollectionName">
  {{> pagesNav}}
  {{> pages}}
</template>
```
I could include it in other templates in several places.

**Comment by alethes** [comment]
Note that the *template* option can be used to specify the name of your template.

**Comment by rizkysyazuli** [comment]
@alethes yes. i finally figure that out (didn't read the manual :smile:). coz at first i thought the template has to be *exactly* the same name with the collection.

**Comment by aurerua** [comment]
@alethes Thanks for the clarification. (I don't know why I didn't see that :S )
