### ISSUE TITLE
can't click on pagesNav buttons without jumping to last page

### ISSUE THREAD

**Issue by hartwoolery** [alethes/meteor-pages#139]
If click on any navigation page in pagesNav, results in subscribing to all documents, and last pagesNav button is highlighted.  If I click on any other button, it remains on last page.  Would seem that something is causing it to page improperly?

My options:

{
divWrapper: false
homeRoute: "/analytics/documents/"
itemTemplate: "analyticsDocumentsRow"
perPage: 10
route: "/analytics/documents/"
router: "iron-router"
routerLayout: "bodyLayout"
routerTemplate: "analyticsDocuments"
templateName: "analyticsDocuments"
}

**Comment by hartwoolery** [comment]
For anyone else having a similar issue, using the reactive Router.current() within another Iron Router onBeforeAction hook was the culprit.

**Comment by cismous** [comment]
I also encountered this issue, can you explain how you solved?

**Comment by cismous** [comment]
hartwoolery, could you reopen this?
