### ISSUE TITLE
Exclude/Include Fields on Subscription 

### ISSUE THREAD

**Issue by johannbotha** [alethes/meteor-pages#151]
Hey guys, 

I'm looking to exclude certain fields from my pages subscription with the pages constructor. For example,

If I currently have

```coffeescript
@Animals = new Meteor.Collection 'animals'

@SearchAnimalPages = new Meteor.Pagination Animals,
  templateName: "animals"
  itemTemplate: "animalItem"
  perPage: 50
  dataMargin: 0
  availableSettings:
    filters: true
```

But I want to exclude a field. Lets say I want to exclude the 'secret' field on the animal document. 

`> db.animals.find({}, {"secret" : 0} )`

Is there currently a way to do this with the pages package? If not, where would be the best place to add this?

**Comment by Roylib** [comment]
I'm having the same issue.
I don't want the secret document fields to be sent over in the web socket.

@johannbotha have you found a solution for this?

**Comment by johannbotha** [comment]
@Roylib 

The general idea is that you want to add an `auth` function on the pagination object. We found that the count query wasn't respecting the auth function so we forked the package and fixed it here. Feel free to use our fork. 

https://github.com/electronifie/meteor-pages/commit/c3528945b839220202cc74242b63302bfa385453

**Comment by Roylib** [comment]
Thanks! I'll use it.

When I tried using "auth" (from the original branch), all of the query items were returned into the first page, leaving the other pages empty.
Can you please share a masked example of your implementation of the "auth" function?

**Comment by Roylib** [comment]
I've used a [similar answer] (https://github.com/alethes/meteor-pages/issues/131) to come up with the usage below.
I'm sure that it will help someone in the future, because the documentation is very poor.

If you have a better solution, please share.

```javascript
this.Houses = new Meteor.Pagination(HousesCollection, {
    templateName: "houses",
  	itemTemplate: "houseItem",
    perPage: 2,
  	sort: { timestamp: -1 },
    auth: function(skip, sub) {
        //Edit custom settings if required:
        var customSettings = {};
        customSettings.fields = {address: 1}; //This is the only field that will be shown
      	customSettings.filters = {baths: 3} //Show houses with 3 baths only

        //Leave this part untouched:
        var fields = customSettings.fields || this.fields
            , sort = customSettings.sort || this.sort //Since I haven't supplied this field, the Pagination sort I've configured above will be used (=2)
            , perPage = customSettings.perPage || this.perPage //Same as the line above
            , _filters = customSettings.filters || this.filters 
            , _options = { fields: fields, sort: sort, limit: perPage, skip: skip };
        return [ _filters, _options ];
    }
});
```
