### ISSUE TITLE
Where is pages3 demo code ?

### ISSUE THREAD

**Issue by nmgwddj** [alethes/meteor-pages#187]
I'm sorry, I'm not good at English.
I want the code to learn http://pages3.meteor.com/, ask whether you can provide a little?

**Comment by sjmcdowall** [comment]
All the examples are in the "examples" directory under the source.  Here is a link to the one that I believe is for pages3:

https://github.com/alethes/meteor-pages/tree/master/examples/infinite

**Comment by nmgwddj** [comment]
@sjmcdowall Thanks！
