### ISSUE TITLE
Is client-side filtering broken with the current ver. of Meteor?

### ISSUE THREAD

**Issue by elliotberry** [alethes/meteor-pages#199]
I've seen this come up a couple of times in the history of this repo - I'm getting the "Changing filters not allowed." when using Pages.set() on the client. Anyone else seeing this? Thanks.

**Comment by elliotberry** [comment]
When I allow it in availableSettings it works, but is this the preferred use?

**Comment by awrichar** [comment]
I think that's exactly the purpose of availableSettings (to control what can be changed from the client). This can probably be closed.

**Comment by elliotberry** [comment]
Please do, I'm a dumbass :100:
