### ISSUE TITLE
Meteor 1.3 : Helpers dictionary has to be an object

### ISSUE THREAD

**Issue by bletual** [alethes/meteor-pages#203]
hi,

Exception : Uncaught Error: Helpers dictionary has to be an object
In blaze.js, "dict" is undefined :

Template.prototype.helpers = function (dict) {                                                                         // 443
  if (! _.isObject(dict)) {                                                                                            // 444
    throw new Error("Helpers dictionary has to be an object");                                                         // 445
  }  

Call from "alethes_pages.js" :
Template.prototype.helpers = function(dict) {                                                                          // 1294
  global._TemplateHelpers[this.viewName.substr(9)] = dict;                                                             // 1295
  return th.apply(this, arguments);                                                                                    // 1296
};  

The exception when "return th.apply(this, arguments);"

Is about : pages_blablabla_pagesNavCont ...

Tkanks,

Bruno.

**Comment by Geekat-Manu** [comment]
Got the same ! I try to downgrade to Meteor 1.2 and it works again.

**Comment by bletual** [comment]
Thanks.

Do you know if it will be ok soon ?

Bruno.

**Comment by Geekat-Manu** [comment]
I've no idea... It depends on @alethes ;)

**Comment by bletual** [comment]
ok :-)

**Comment by wesleyfsmith** [comment]
Having the same problem here. Would love to find a solution.

**Comment by Geekat-Manu** [comment]
The last commit was made in june 2015... I've many work for now, but if no one make a fix at the end of the next week, I'll do it !

**Comment by alethes** [comment]
I've just fixed it.

**Comment by wesleyfsmith** [comment]
@alethes Thank you so much, really appreciate it.

**Comment by Geekat-Manu** [comment]
Thanks @alethes :)

**Comment by bletual** [comment]
Thanks a lot

**Comment by Bryanale** [comment]
Updated my meteor and this error still occurs.

**Comment by alethes** [comment]
Try 'meteor update alethes:pages'.
