### ISSUE TITLE
Doesn't work on Meteor 1.3.3

### ISSUE THREAD

**Issue by exKAZUu** [alethes/meteor-pages#211]
When I run `meteor update --release 1.3.3` and `meteor run`, I got the following error message.

```
W20160612-09:51:00.230(9)? (STDERR) /Users/USER_NAME/.meteor/packages/meteor-tool/.1.3.3.1krlhd6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160612-09:51:00.230(9)? (STDERR)             				throw(ex);
W20160612-09:51:00.231(9)? (STDERR)             				      ^
W20160612-09:51:00.232(9)? (STDERR) ReferenceError: require is not defined
W20160612-09:51:00.232(9)? (STDERR)     at Package (packages/alethes_pages.js:45:16)
W20160612-09:51:00.233(9)? (STDERR)     at packages/alethes_pages.js:1296:4
W20160612-09:51:00.233(9)? (STDERR)     at packages/alethes_pages.js:1303:3
W20160612-09:51:00.233(9)? (STDERR)     at /Users/USER_NAME/Projects/APP_NAME/.meteor/local/build/programs/server/boot.js:291:10
W20160612-09:51:00.234(9)? (STDERR)     at Array.forEach (native)
W20160612-09:51:00.235(9)? (STDERR)     at Function._.each._.forEach (/Users/USER_NAME/.meteor/packages/meteor-tool/.1.3.3.1krlhd6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160612-09:51:00.236(9)? (STDERR)     at /Users/USER_NAME/Projects/APP_NAME/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

**Comment by wesleyfsmith** [comment]
Same issue here, would be great to get this fix merged in.

**Comment by exKAZUu** [comment]
A quick workaround may be to copy `client` and `lib` into `lib` of your project, and copy `public/loader.gif` into `public` of your project instead of the usage of meteor-pages package.

Actually, I tried to create the following directories and file.
```
MY_APP/lib/meteor-pages/client
MY_APP/lib/meteor-pages/lib
MY_APP/public/loader.gif
```

I confirmed that the above-mentioned problem is removed, but, I faced with another problem (maybe related to fast-render), so I didn't check whether my workaround works well or not.

**Comment by exKAZUu** [comment]
In addition to the above-mentioned file copy, I added the following code at the heads of `MY_APP/lib/meteor-pages/client/controllers.coffee` and `MY_APP/lib/meteor-pages/lib/pages.coffee`.

```
`import { _ } from 'meteor/underscore';`
```

Finally, I confirmed that my app worked well!

**Comment by gantrim** [comment]
I didnt have to do any of the above but I was getting the same error message. I followed the solution reported [here](https://github.com/meteor/meteor/issues/7226) by @benjamn.

In [lib/pages.coffee  line 106](https://github.com/alethes/meteor-pages/blob/master/lib/pages.coffee#L106) replace:

```
throw new Meteor.Error "missing-new", "The Meteor.Pagination instance has to be initiated with `new`"
```

with:
```
throw new Meteor.Error "missing-new", "The Meteor.Pagination instance has to be initiated with 'new'"
```

I have submitted PR #214 to fix this issue. In the meantime you are welcome to use [my fork](https://github.com/gantrim/meteor-pages/tree/meteor_1.3.3_require_fix).

**Comment by exKAZUu** [comment]
I confirmed that 1.3.3.1 fixed this issue. So I close it now.
