### ISSUE TITLE
GroundDB integration

### ISSUE THREAD

**Issue by Lauricio** [alethes/meteor-pages#45]
Hey,

Excellent package, thank you! I was trying to integrate it with [GroundDB](https://github.com/GroundMeteor/Meteor-GroundDB) for offline use together with `appcache` package with no luck. When i try to pass a `grounded` meteor collection and open up the app offline i see that `Pages.Collection._collection._docs._map` is populated by grounddb, but `Pages.PaginatedCollection._collection._docs._map` is empty. I am not used to coffeescript and not sure whats going on exactly but it looks that when offline pages stops on `reload` method. Perhaps there could be some kind of fallback if app is offline and `grounddb` is present to use the locally stored documents?

**Comment by alethes** [comment]
Please check out the newest version of this repository. It should integrate nicely with GroundDB. I made a couple of structural changes and the end product has to be tested before I release it on Atmosphere. There's a GroundDB demo in the examples directory.

To install the package directly from the GitHub repo, run:
```
mkdir -p packages
git clone https://github.com/alethes/meteor-pages packages/pages
meteor add alethes:pages
from your app's root directory.
```

I look forward to hearing your feedback.

**Comment by almogdesign** [comment]
Any quick documentation?

**Comment by almogdesign** [comment]
Tried testing it out but didn't even get to the offline test. I'm not seeing anything when I'm online. 

Here is my code 
Pages = new Meteor.Pagination("Forms", {
    perPage: 20
});

{{> pages}}
{{> pagesNav}}

Not seeing anything maybe I'm missing something?

**Comment by alethes** [comment]
Strange... Your code seems almost identical to the basic example, which seems to work normally with the latest commit. There's also a new GroundDB example. To try out one of the examples, run:
```
git clone https://github.com/alethes/meteor-pages meteor-pages
cd meteor-pages/examples/grounddb
meteor
```

**Comment by almogdesign** [comment]
@alethes yea I'm not getting any errors either. How does the 

{{> pages}}
{{> pagesNav}}

Work, maybe I don't have the templates defined right

**Comment by alethes** [comment]
First of all, did you run the *basic* example? Does it work for you? There are complete Meteor apps in the *examples* directory and you can compare your app with them. I just checked and both *basic* and *grounddb* work fine when pulled from the master branch. Just run:
```
git clone https://github.com/alethes/meteor-pages meteor-pages
cd meteor-pages/examples/grounddb
meteor

```
and I'm sure it'll work.

---
As for `{{> pages}}` and `{{> pagesNav}}`, they're both [helpers that return a template](https://github.com/meteor/meteor/wiki/Using-Blaze#templatefoo-is-not-a-function-and-does-not-return-a-string). They're defined exclusively on the main pagination template which, by default is expected to have the same name as the paginated collection. Use the *templateName* option to use a different template as a container for pagination components.
