### ISSUE TITLE
Get parameters from iron-router to pass to Meteor.Pagination

### ISSUE THREAD

**Issue by geekyme** [alethes/meteor-pages#51]
Hello, 

I have a page /post/12840 (route: /post/_id)

I want to take the _id in the route parameters and pass it to Meteor.Pagination. How do I do that?

**Comment by thpoul** [comment]
+1 Bump

**Comment by alethes** [comment]
Although the question was problematic at the time of posting, it's quite easy to leverage route parameters now. Please have a look at the [iron-router example](https://github.com/alethes/meteor-pages/blob/master/examples/iron-router/main.coffee#L27). There's an optional *group* parameter in the *route*. It's used in [*routeSettings*](https://github.com/alethes/meteor-pages/blob/master/examples/iron-router/main.coffee#L31) (a function called from the defined route's *onBeforeAction*).
