### ISSUE TITLE
adjust the publication / subscription name through settings

### ISSUE THREAD

**Issue by dohomi** [alethes/meteor-pages#56]
Hi, 
I just tried your plugin for my blog extension. But unfortunately it's not possible having multiple collection pages on one page/route, because the publication name is always the same. Would be nice if through settings the publication name could get edited. I have on the sidebar latest/mostviewed pages of the same collection but currently this is not supported.
Cheers

**Comment by williamkhshea** [comment]
@dohomi I am using publishComposite too and I want to do collection joins on pages. How are you doing collection joins with meteor-pages at the moment?

**Comment by dohomi** [comment]
@williamkhshea I'm not using this package at the moment. Back then I decided to write my pub/sub without any package.
