### ISSUE TITLE
How to sort at 'infinite'

### ISSUE THREAD

**Issue by jacksmu** [alethes/meteor-pages#63]
Hi, I want to made a new 'sort' at infinite mode, but after 'PatientPage.set', the sort not change, it also is the old sort. How to made a new sort at 'infinite' mode? Thanks.

**Comment by GFargo** [comment]
:+1: Always nice to share :wink:

**Comment by netmobile** [comment]
We actually had problem with meteor-pages.  It was leaking many records through and we have no control over what was published.  We had to remove this package and do something custom for infinite scroll.

**Comment by GFargo** [comment]
@netmobile hmm, I feel like I've been experiencing similar issues.  The issue appears to be that it ignores sort params & when `infinite` is activated it just loads all documents on page load.  

Was thinking about trying to implement Solution #1 listed [here](https://www.discovermeteor.com/blog/pagination-problems-meteor/)

**Comment by sjmcdowall** [comment]
Guys -- you may want to look at the fork of this project -- https://atmospherejs.com/electronifiejs/pages -- it appears to be more active ..
