### ISSUE TITLE
Table Time Format

### ISSUE THREAD

**Issue by majimboo** [alethes/meteor-pages#68]
What if I wanted to display a table that has time? Currently if I include the `createdAt` property it shows: `Fri Oct 10 2014 17:24:31 GMT+0800 (PHT)`

**Comment by alethes** [comment]
This is, above all, a pagination package. It's main purpose is to enable displaying, and navigating between, subsets of arbitrarily large collections. Extending the *table* functionality seems to go beyond the scope of this package, especially when it's so easy to create all kinds of tables using your own templates. Below, you'll find a solution more or less equivalent to what the *table* option does behind the scenes. By passing similar templates to the `Meteor.Pagination` constructor and defining a suitable template helper for *tableRow.attributes* (eg. using `momentjs` to parse datetime fields, as @fix suggests), you can achieve all kinds of transformations.
```html
<template name="table">
  {{> pagesNav}}
  <table class="{{class}}">
    <thead>
      <tr>
        {{#each header}}
          <th>{{value}}</th>
        {{/each}}
      </tr>
    </thead>
    <tbody>
      {{> pages}}
    </tbody>
  </table>
</template>

<template name="tableRow">
  <tr>
    {{#each attributes}}
      <td>{{value}}</td>
    {{/each}}
  </tr>
</template>
```

```javascript
this.MyCollection = new Meteor.Collection("myCollection");
this.Pages = new Meteor.Pagination(MyCollection, {
  template: "table",
  itemTemplate: "tableRow"
});
```
