### ISSUE TITLE
Uncaught TypeError: Cannot read property 'helpers' of undefined

### ISSUE THREAD

**Issue by almogdesign** [alethes/meteor-pages#95]
I'm getting the following error, my code is based on the basic example 
Uncaught TypeError: Cannot read property 'helpers' of undefined

**Comment by winstoncse** [comment]
seems like the order of how your define your package matters, inside my package.js, i put the common file I used to call new Meteor.Pagination last, so the depended Template could be loaded before Pages.coffee runs and it works :D 

this.Pages = new Meteor.Pagination({
  templateName: "yourTemplateName",
  ...
});

api.add_files([
    'lib/common/pagination/common.js'
  ], ['client', 'server']);

**Comment by diego2013** [comment]
I got here due to the same issue. What @alethes  said solved the problem for me. Just wanted to point out that the documentation (meaning, the README.md file) instructs to use 

     this.Pages = new Meteor.Pagination("collection-name", {
      **itemTemplate**: "myItemTemplate"
    })

This crashed in my code (iron router could not find the routes and the helpers couldn't be found either). Everything got fixed by using 

     this.Pages = new Meteor.Pagination("collection-name", {
      ** templateName**: "myItemTemplate"
    })

Should the README.md be corrected or is there something else I don't understand going on when passing the template name to the pagination constructor?

**Comment by metalik** [comment]
I am using v1.8.4 and also got this Uncaught TypeError: Cannot read property 'helpers' of undefined

I am using iron-router and have already provide the routerTemplate and itemTemplate settings

```javascript
this.Pages = new Meteor.Pagination(Posts, {
  router: "iron-router",
  homeRoute: "/",
  route: "/",
  routerTemplate: "postsList",
  routerLayout: "layout",
  itemTemplate: "postItem"
});
```

**Comment by alethes** [comment]
Try using *templateName* instead of *routerTemplate*.

**Comment by metalik** [comment]
Got blank page when using templateName instead of routerTemplate 
However, it works when I have specified both templateName and routerTemplate

**Comment by valorloff** [comment]
```
router: "iron-router",
  homeRoute: "/lastupdates",
  route: "/lastupdates",
  templateName: "adminLastUpdates",
  routerLayout: "adminNav",
  itemTemplate: 'adminProduct',
  sort: {'lastmod': -1}
```
Uncaught TypeError: Cannot read property 'renderFunction' of undefined

**Comment by valorloff** [comment]
```
Pages = new Meteor.Pagination('Products', {
  router: 'iron-router',
  route: '/lastupdates/',
  routerTemplate: 'adminLastUpdates',
  templateName:   'adminLastUpdates',
  routerLayout: "adminNav",
  itemTemplate: 'adminProduct',
  sort: {'lastmod': -1}
  });
```
Uncaught TypeError: Cannot read property 'renderFunction' of undefined

**Comment by PrakashSasi** [comment]
how to use this Package in meteor . i dont understand your Example and Read me file
