### ISSUE TITLE
Question: Can Meteor-Pages support search & filters? 

### ISSUE THREAD

**Issue by markudevelop** [alethes/meteor-pages#97]
Hello,

I love this package it's really useful and great job on creating it, I still need few more features for my project like Search (Important) Filters (Not so much but maybe useful). And wanted to know if it's planned to be supported? Or can this even be added? 

Thank you.

**Comment by stlouisweb** [comment]
This doesn't work, logs a message "Changing filters is not allowed".

**Comment by alethes** [comment]
You need to pass eg. *{availableSettings: {filters: true}}* to the Pagination constructor.

**Comment by stlouisweb** [comment]
That does the trick.  Thanks!
